apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rpwb10gx7-go-gitops
  description: This is GitOps manifest for rpwb10gx7-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rpwb10gx7-go
    backstage.io/kubernetes-id: rpwb10gx7-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rpwb10gx7-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rpwb10gx7-go
